# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AigensSdkDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AigensSdkDemo
  #pod 'aigens-sdk-core', '0.0.3'
  pod 'aigens-sdk-core', :path => '../../../aigens-sdk/ios/aigens-sdk-core/'

end
